# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0800e1126f7475b45e8add1191fcbd0e6f69dc19463f65a39d0df09b746712f72b8681512596ae74d140bce6cd822f4f7fc7ae03c062444bdee982ddb33bd99
  project_id: gurpreet-glass-1192
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://accounts.google.com/o/oauth2/token

  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_id: 159161993995-7vcp2n567ks8t0lbhrt18ag1gvll9j7i.apps.googleusercontent.com,
  client_secret: okEmqHQ6L03P4rWqihiXScps
test:
  secret_key_base: a2da8c0e9e1e6e19d6da66be1227aa5278a3126d23569e6693221442a4b9ae53922a117025e65952e5dad6d5e16b357cef9c0267d9bbc95aa65ce50f93c33684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
